insert into USERS(USERNAME, PASSWORD, ENABLED, ROLE)values('user','$2y$12$jKN42X./NkvR..V/88tSk.SNJ9U3N98wCe5P/pV8vCvgwsHCcP90u',true,'ROLE_USER');
insert into USERS(USERNAME, PASSWORD, ENABLED, ROLE)values('admin','$2y$12$jKN42X./NkvR..V/88tSk.SNJ9U3N98wCe5P/pV8vCvgwsHCcP90u',true,'ROLE_ADMIN');


insert into STOCKS(STOCK_ID,STOCK_NAME, CURRENT_PRICE, LAST_UPDATE)values(1,'Google',250.30, CURRENT_TIMESTAMP());
insert into STOCKS(STOCK_ID,STOCK_NAME, CURRENT_PRICE, LAST_UPDATE)values(2,'MicroSoft',150.30, CURRENT_TIMESTAMP());
insert into STOCKS(STOCK_ID,STOCK_NAME, CURRENT_PRICE, LAST_UPDATE)values(3,'Amazon',250.00, CURRENT_TIMESTAMP());
insert into STOCKS(STOCK_ID,STOCK_NAME, CURRENT_PRICE, LAST_UPDATE)values(4,'LinkedIn',175.30, CURRENT_TIMESTAMP());
insert into STOCKS(STOCK_ID,STOCK_NAME, CURRENT_PRICE, LAST_UPDATE)values(5,'Facebook',290.99, CURRENT_TIMESTAMP());
insert into STOCKS(STOCK_ID,STOCK_NAME, CURRENT_PRICE, LAST_UPDATE)values(6,'TCS',350, CURRENT_TIMESTAMP());
insert into STOCKS(STOCK_ID,STOCK_NAME, CURRENT_PRICE, LAST_UPDATE)values(7,'Infosys',280, CURRENT_TIMESTAMP());
insert into STOCKS(STOCK_ID,STOCK_NAME, CURRENT_PRICE, LAST_UPDATE)values(8,'Accenture',600, CURRENT_TIMESTAMP());