DROP TABLE IF EXISTS STOCKS;
DROP TABLE IF EXISTS USERS;


CREATE TABLE STOCKS (
  STOCK_ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  STOCK_NAME VARCHAR(250) NOT NULL,
  CURRENT_PRICE DECIMAL(10,2) NOT NULL,
  LAST_UPDATE TIMESTAMP NULL
);

create table USERS (
    USERNAME VARCHAR(50) NOT NULL PRIMARY KEY,
    PASSWORD VARCHAR(120) NOT NULL,
    ENABLED BOOLEAN NOT NULL,
    ROLE VARCHAR(50) NOT NULL

);

